[target.thumbv7em-none-eabihf]
rustflags = [
  "-C",
  "link-arg=-Tlink.x",
  "-C",
  "link-arg=--nmagic",
  "-C",
  "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"
target-dir = "embedded-target" 

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip STM32F401RCTx"

[env]
DEFMT_LOG = "trace"
